language: node_js
node_js:
- '6.9'
- '7.5'
before_install: npm i -g itbldz
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- build-it
- cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage --language typescript
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: oMJCb4/gBVZ5Q+E5KSBFbOAzxe0q31udxPjkOEPzeBUSXUzfV2EQ0FJ3ykHCUoKceIfmgjOeOgEOmnAPOKkRLL3sMrhSICaBzm/d4G50OMnDaA3bnMwKIqABrU0h5F9ZCLJtdBnDvd99w7IresdqvU192UKSqNRE2Sh5DsyB/BVaPPERhOOFJeuRJiRZ6DsJ3y7u6X29e//C4PaXUIb7SESnaDBtEd+RyMlna76aiRnCnR6Hyxfxejsh6weaaQrcwDnuPJW6b3SqiTHCIJBnnoL8ymmbR7ngxZyVl2NkuhEae6LIpGH+PjSdt6HiqVMh7KRY/OvsInBW3Oq8miomooDxCeQtZlboaQ+H00/gcMfydssdb0BrtU4D00ab3lZ7acu+/5hsVZcxTw/ZTR0a5JCAdm0XXyXKjyxeJf9yxYCi07IX73foAQxVMU+nNjbyRY2Cyn0ye52UjqPnKT1TE9blK5lOa+dpLywcti2HaDUVE7eLTc4LNtMdzHodeuC4KUhO6dXYoznw+DZ1lQy5TTy4Yl1HaACAOboQjKTbeC9DOWHIKmv80pG4uexsvVbqKaiPWK6IYacestN15KUDQozz9XUMjVNBjNalm9VpVCkDtGTGd/+ig8yPG7/qJkQkg5EKjxUX6yrx++Asnu24+KTDB8Zs2GxNECFXaDZYXG8=
  app: robbie-the-robot
  on:
    repo: MatthiasKainer/robbie-the-robot
