language: node_js
node_js:
- '6.9'
- '7.5'
before_install: npm i -g itbldz
script:
- build-it
- cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage --language typescript
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: ypXDe82LQwXHKEauJmGQ2OnYiU/5whFVKnSMpTEYppYfD02Xzr9mAHggl4NsdhPh5B4p0WEnZ5VP2rKDTnX3wiGNkJPgois6zXSfUCBsKfRYB92Va7Zg/wl4ahSABUAwPrqkUY1zxc+Op7Z8NXrQauIG7EzCIgO9gsLG2pyr0GijiwhP4Ak51wmDa8p97yKDhNtfy039TfaIDncjuh+QJBdCogiEo7lrpBx3Z4VeJCMXODaQViuXLUQC61Vz2t/ux7tWKbzme6FIgFvJeXh8dI54fFhBzrYpVrAkmIjKnIQhAm0r8ZxGTX3QJuU4Zzo90Q7T5g/quGzYXy7MO5+C9fD78u5gjU4erGm81X8DrnnNk/93IiGv2DrGHFYtd6/r9Wucr2p9W7GDSToXHWBaHkZvUMFpHBcGiN5tMuMLB4AHZPyofEAz8UH6jYRiD7W9cOZBCa42jESoSxQ0GUbTbggowgI5APGwq9rvSZ7oxo47ZNkWxow2+TgvRYejAGjr+bGdnRugFH7FAeJwFXam9fasBP8zJTV02iflYXXNR8UX/7AEjbTRQloMLeNr88e2dOlZY2T4aGG07f4B4a8PdJNtVyx6bgi1S9E7idu3GXpBHM3iZXSjO/Ez9BJro4O9OAelecVnGKj3UcLNgFn3nnc3WRa6WI9Rs8bDFImH+nk=
  app: robbie-the-robot
  on:
    repo: MatthiasKainer/robbie-the-robot
